user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /

gestion_projet:
    resource: "@GestionProjetBundle/Resources/config/routing.yml"
    prefix:   /

  
# app/config/routing.yml
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin  
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin 
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    