# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.departement:
        class: Myapp\GestionProjetBundle\Admin\DepartementAdmin
        arguments: [~, Myapp\GestionProjetBundle\Entity\Departement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Departement }
            
    admin.Employe:
        class: Myapp\GestionProjetBundle\Admin\EmployeAdmin
        arguments: [~, Myapp\GestionProjetBundle\Entity\Employe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Employe }     
    admin.Projet:
        class: Myapp\GestionProjetBundle\Admin\ProjetAdmin
        arguments: [~, Myapp\GestionProjetBundle\Entity\Projet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Projet }  
            
    # app/config/services.yml
services:
    app.form.registration:
        class: Myapp\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }        